require('vanilla_options')
require('vanilla_plus')
require('big_file')
require('plug')
require('treesitter')
require('lsp')
require('dap_setup')
pcall(function() require('dap_configs') end) -- Source manually to get errors
require('telescope_')
require('blink')
require('theme')
require('lsp')
